AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation Template für eine EC2 Instanz mit t2.micro und Security Group für Port 80 und 443 3'

Resources:
  welf_l4SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group für welf_l4 EC2 Instance
      GroupName: welf-l4-security-group
      SecurityGroupIngress:
        - IpProtocol: tcp  # Korrekt: TCP ist das Transportprotokoll für HTTP
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: "HTTP"
        - IpProtocol: tcp  # Korrekt: TCP ist das Transportprotokoll für HTTPS
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: "HTTPS"

  welf_l4EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-06d289e97e14eade2
      SecurityGroups:
        - !Ref welf-l4SecurityGroup

  
  welf_l4SecurityGroupId:
    Description: ID der Security Group
    Value: !Ref welf-l4SecurityGroup
